import { Layout } from "@/components/Layout/Layout";
import { AppBar } from "@/components/Navbar";
import {
  Container,
  Image,
  Text,
  Grid,
  Divider,
  Spacer,
  Button,
  Row,
  Card,
  Link,
  Tooltip,
} from "@nextui-org/react";
import Head from "next/head";

export default function Home() {
  const list = [
    {
      title:
        "มอบเกียรติบัตรนักเรียนที่เข้าร่วมการอบรมเชิงปฏิบัติการประวัติศาสตร์ท้องถิ่นกับศิลปะดิจิทัล (opens in a new tab)",
      img: "https://www.thr.ac.th/wp-content/uploads/2023/03/get-cer-social-2565.webp",
      date: "มีนาคม 3, 2023",
    },
    {
      title: "กิจกรรมปัจฉิมนิเทศ ประจำปีการศึกษา 2565 (opens in a new tab)",
      img: "https://www.thr.ac.th/wp-content/uploads/2023/03/congrat-2565.webp",
      date: "มีนาคม 3, 2023",
    },
    {
      title: "มอบเกียรติบัตร งานศิลปหัตถกรรมนักเรียน ระดับชาติ ครั้งที่ 70",
      img: "https://www.thr.ac.th/wp-content/uploads/2023/03/get-skill-cer-2565.webp",
      date: "มีนาคม 3, 2023",
    },
    {
      title: "ประชุมผู้ปกครอง ปีการศึกษา 2565",
      img: "https://www.thr.ac.th/wp-content/uploads/2023/01/meeting-2565.webp",
      date: "มีนาคม 3, 2023",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <Grid className="relative">
        <Image
          src="https://preview.redd.it/rlw2096pong71.png?auto=webp&s=db577ceb8236ee5efeb8a3aea2ee7189eb87e45f"
          alt="Image"
          className="md:w-full"
          css={{
            "@smMax": {
              h: "auto",
            },
          }}
        />
        <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-50">
          <div className="w-2/4 text-white">
            <Button
              color={"default"}
              shadow
              className="md:text-3xl text-white drop-shadow-md"
              css={{
                "&:after": {
                  content: '""',
                  position: "absolute",
                  width: "100%",
                  height: "100%",
                  opacity: 1,
                  borderRadius: "$pill",
                  transition: "all 0.4s ease",
                },
                "&:hover": {
                  transform: "translateY(-5px)",
                  "&:after": {
                    transform: "scaleX(1.5) scaleY(1.6)",
                    opacity: 0,
                  },
                },
                "&:active": {
                  transform: "translateY(-2px)",
                },
                "@smMax": {
                  fontSize: "$xs",
                },
              }}
            >
              โรงเรียนทุ่งใหญ่เฉลิมราช - สถานศึกษาเพื่อการเรียนรู้และพัฒนาทักษะ
            </Button>
            <Spacer />
            <Text
              className="whitespace-pre-line text-white/60 drop-shadow-md"
              css={{
                "@smMax": {
                  fontSize: "$sm",
                },
              }}
            >
              โรงเรียนทุ่งใหญ่เฉลิมราชเป็นสถานศึกษาที่ให้ความสำคัญกับการเรียนรู้และพัฒนาทักษะของนักเรียน
              ด้วยทีมครูที่มีคุณภาพและมีประสบการณ์ในการสอน
              โรงเรียนเรามุ่งเน้นให้การเรียนการสอนเป็นประสบการณ์ที่น่าสนใจและมีคุณค่า
              นอกจากนี้
              เรายังมีสถานที่เรียนรู้ที่ทันสมัยและอุปกรณ์การเรียนรู้ที่ทันสมัยเพื่อส่งเสริมให้นักเรียนได้พัฒนาทักษะที่จำเป็นในสายอาชีพของอนาคต
              มาร่วมเรียนรู้และเติบโตกับเราที่โรงเรียนทุ่งใหญ่เฉลิมราชวันนี้!
            </Text>
          </div>
        </div>
        <div className="icon-scroll"></div>
      </Grid>
      <div className="pt-12">
        <div className="justify-center justify-items-center text-center">
          <Text
            className="text-blue-400 drop-shadow-md"
            css={{
              fontSize: "$4xl",
            }}
          >
            กิจกรรมภายใน รร...
          </Text>
          <Grid.Container gap={2} justify="flex-start">
            {list.map((item, index) => (
              <Grid xs={4} sm={3} key={index}>
                <Tooltip content={item.date}>
                  <Card isPressable>
                    <Card.Body css={{ p: 0 }}>
                      <Card.Image
                        src={item.img}
                        objectFit="cover"
                        width="100%"
                        height={140}
                        alt={item.title}
                      />
                    </Card.Body>
                    <Card.Footer css={{ justifyItems: "flex-start" }}>
                      <Row wrap="wrap" justify="space-between" align="center">
                        <Text
                          b
                          css={{
                            fontSize: "$sm",
                          }}
                        >
                          {item.title}
                        </Text>
                      </Row>
                    </Card.Footer>
                  </Card>
                </Tooltip>
              </Grid>
            ))}
          </Grid.Container>
          <Spacer y={4} />
          <Container>
            <Grid.Container gap={2} justify="center">
              <Grid xs={6} sm={3}>
                <Link
                  href="https://instagram.com/avaevolve"
                  css={{ textAlign: "left" }}
                  target="_blank"
                >
                  <a className="social-card-link">
                    <Card
                      css={{
                        minHeight: "140px",
                        backdropFilter: "saturate(180%) blur(14px)",
                        background: "rgba(255, 255, 255, 0.05)",
                        padding: "16px",
                      }}
                      className="social-card"
                    >
                      <Card.Header
                        css={{
                          display: "flex",
                          padding: "0px",
                          rowGap: "10px",
                        }}
                      >
                        <img
                          src="https://seeklogo.com/images/I/instagram-logo-1494D6FE63-seeklogo.com.png"
                          height={28}
                          width={28}
                        />
                        <Text h5 size="$md" css={{ m: 0, marginLeft: "10px" }}>
                          300 / คน
                        </Text>
                      </Card.Header>
                      <Spacer y={0.5} />
                      <Card.Body css={{ padding: "0px" }}>
                        <Text color="$accents8">
                          จำนวนนักเรียน-บุคคลากรทั้งหมด{" "}
                        </Text>
                      </Card.Body>
                    </Card>
                  </a>
                </Link>
              </Grid>
              <Grid xs={6} sm={3}>
                <Link href="https://discord.gg/Yg3dVzaDqp" target="_blank">
                  <a className="social-card-link">
                    <Card
                      css={{
                        minHeight: "140px",
                        backdropFilter: "saturate(180%) blur(14px)",
                        background: "rgba(255, 255, 255, 0.05)",
                        padding: "16px",
                      }}
                      className="social-card"
                    >
                      <Card.Header
                        css={{
                          display: "flex",
                          padding: "0px",
                          rowGap: "10px",
                        }}
                      >
                        <svg height="30" viewBox="0 0 24 24" width="30">
                          <path
                            d="M14.82 4.26a10.14 10.14 0 0 0-.53 1.1 14.66 14.66 0 0 0-4.58 0 10.14 10.14 0 0 0-.53-1.1 16 16 0 0 0-4.13 1.3 17.33 17.33 0 0 0-3 11.59 16.6 16.6 0 0 0 5.07 2.59A12.89 12.89 0 0 0 8.23 18a9.65 9.65 0 0 1-1.71-.83 3.39 3.39 0 0 0 .42-.33 11.66 11.66 0 0 0 10.12 0q.21.18.42.33a10.84 10.84 0 0 1-1.71.84 12.41 12.41 0 0 0 1.08 1.78 16.44 16.44 0 0 0 5.06-2.59 17.22 17.22 0 0 0-3-11.59 16.09 16.09 0 0 0-4.09-1.35zM8.68 14.81a1.94 1.94 0 0 1-1.8-2 1.93 1.93 0 0 1 1.8-2 1.93 1.93 0 0 1 1.8 2 1.93 1.93 0 0 1-1.8 2zm6.64 0a1.94 1.94 0 0 1-1.8-2 1.93 1.93 0 0 1 1.8-2 1.92 1.92 0 0 1 1.8 2 1.92 1.92 0 0 1-1.8 2z"
                            fill="#7289DA"
                          ></path>
                        </svg>
                        <Text h5 size="$md" css={{ m: 0, marginLeft: "10px" }}>
                          24 / ห้อง
                        </Text>
                      </Card.Header>
                      <Spacer y={0.5} />
                      <Card.Body css={{ padding: "0px" }}>
                        <Text color="$accents8">
                          จำนวนห้องเรียนทั้งหมดตั้งแต่ ม1-ม6 ทุกระดับชั้น
                        </Text>
                      </Card.Body>
                    </Card>
                  </a>
                </Link>
              </Grid>
              <Grid xs={6} sm={3}>
                <Link
                  href="https://linkedin.com/company/ava-evolve"
                  target="_blank"
                >
                  <a className="social-card-link">
                    <Card
                      css={{
                        minHeight: "140px",
                        backdropFilter: "saturate(180%) blur(14px)",
                        background: "rgba(255, 255, 255, 0.05)",
                        padding: "16px",
                      }}
                      className="social-card"
                    >
                      <Card.Header
                        css={{
                          display: "flex",
                          padding: "0px",
                          rowGap: "10px",
                        }}
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          x="0px"
                          y="0px"
                          width="30"
                          height="30"
                          viewBox="0 0 48 48"
                        >
                          <path
                            fill="#0288D1"
                            d="M42,37c0,2.762-2.238,5-5,5H11c-2.761,0-5-2.238-5-5V11c0-2.762,2.239-5,5-5h26c2.762,0,5,2.238,5,5V37z"
                          ></path>
                          <path
                            fill="#FFF"
                            d="M12 19H17V36H12zM14.485 17h-.028C12.965 17 12 15.888 12 14.499 12 13.08 12.995 12 14.514 12c1.521 0 2.458 1.08 2.486 2.499C17 15.887 16.035 17 14.485 17zM36 36h-5v-9.099c0-2.198-1.225-3.698-3.192-3.698-1.501 0-2.313 1.012-2.707 1.99C24.957 25.543 25 26.511 25 27v9h-5V19h5v2.616C25.721 20.5 26.85 19 29.738 19c3.578 0 6.261 2.25 6.261 7.274L36 36 36 36z"
                          ></path>
                        </svg>
                        <Text h5 size="$md" css={{ m: 0, marginLeft: "10px" }}>
                          44 / คน
                        </Text>
                      </Card.Header>
                      <Spacer y={0.5} />
                      <Card.Body css={{ padding: "0px" }}>
                        <Text color="$accents8">
                          จำนวนบุคคลากรทั้งหมดภายใน รร เช่น ครู,ผอ,รอง ผอ
                          และอื่นๆ
                        </Text>
                      </Card.Body>
                    </Card>
                  </a>
                </Link>
              </Grid>
            </Grid.Container>
          </Container>
        </div>
      </div>
      <footer className="text-center text-black/40 drop-shadow-md pt-12">
        <a
          href="https://www.facebook.com/imy123r5/"
          className="no-underline text-center text-black/40 drop-shadow-md"
        >
          <p>Copyright © 2023 By wlan0</p>
        </a>
      </footer>
    </>
  );
}
